# Generated by Django 2.2.3 on 2019-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='map_img',
            field=models.ImageField(null=True, upload_to='images', verbose_name=''),
        ),
    ]
